# General Jekyll Config
exclude: [".gitignore", "readme.md", "Gemfile", "Gemfile.lock"]
ga_username: 'UA-367775-15'
permalink: pretty
exclude: [vendor]
gems:
  - jekyll-gist

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-single"
  -
    scope:
      path: ""
      type: tags
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: categories
    values:
      layout: "default"
  -
    scope:
      path: ""
    values:
      images_path: "/assets/images"
      domain: "http://milafrerichs.de"

collections:
  tags:
    output: true
    permalink: /blog/tags/:path
  categories:
    output: true
    permalink: /blog/categories/:path
  projects:

